### ISSUE TITLE
Multiprocessing is not running on M1 MacBook Air - Big Sur 11.2

### ISSUE THREAD

**Issue by galaturka** [RI-imaging/ODTbrain#15]
Hi, 

I correctly installed odtbrain with all dependencies. When I try to run "backprop_from_fdtd_3d.py" or any other examples which includes multiprocessing codes, terminal shows an error like given below. 

I checked from stackoverflow, it seems that multiprocessing codes should be integrated into" __init__", but I could not succeed. Can you please check, if possible ?

Thanks in advance. 

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/gkirabali/opt/miniconda3/envs/myenv/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Users/gkirabali/opt/miniconda3/envs/myenv/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/Users/gkirabali/opt/miniconda3/envs/myenv/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Users/gkirabali/opt/miniconda3/envs/myenv/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/Users/gkirabali/opt/miniconda3/envs/myenv/lib/python3.9/runpy.py", line 268, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/Users/gkirabali/opt/miniconda3/envs/myenv/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Users/gkirabali/opt/miniconda3/envs/myenv/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/gkirabali/examples/backprop_from_fdtd_3d.py", line 37, in <module>
    f = odt.backpropagate_3d(uSin=sinoRytov,
  File "/Users/gkirabali/opt/miniconda3/envs/myenv/lib/python3.9/site-packages/odtbrain/_alg3d_bpp.py", line 486, in backpropagate_3d
    pool4loop = mp.Pool(processes=num_cores,
  File "/Users/gkirabali/opt/miniconda3/envs/myenv/lib/python3.9/multiprocessing/context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
  File "/Users/gkirabali/opt/miniconda3/envs/myenv/lib/python3.9/multiprocessing/pool.py", line 212, in __init__
    self._repopulate_pool()
  File "/Users/gkirabali/opt/miniconda3/envs/myenv/lib/python3.9/multiprocessing/pool.py", line 303, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,
  File "/Users/gkirabali/opt/miniconda3/envs/myenv/lib/python3.9/multiprocessing/pool.py", line 326, in _repopulate_pool_static
    w.start()
  File "/Users/gkirabali/opt/miniconda3/envs/myenv/lib/python3.9/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/gkirabali/opt/miniconda3/envs/myenv/lib/python3.9/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/Users/gkirabali/opt/miniconda3/envs/myenv/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 32, in __init__
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/gkirabali/opt/miniconda3/envs/myenv/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    super().__init__(process_obj)
  File "/Users/gkirabali/opt/miniconda3/envs/myenv/lib/python3.9/multiprocessing/popen_fork.py", line 19, in __init__
    exitcode = _main(fd, parent_sentinel)
  File "/Users/gkirabali/opt/miniconda3/envs/myenv/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/Users/gkirabali/opt/miniconda3/envs/myenv/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Users/gkirabali/opt/miniconda3/envs/myenv/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/Users/gkirabali/opt/miniconda3/envs/myenv/lib/python3.9/runpy.py", line 268, in run_path
    self._launch(process_obj)
  File "/Users/gkirabali/opt/miniconda3/envs/myenv/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    return _run_module_code(code, init_globals, run_name,
  File "/Users/gkirabali/opt/miniconda3/envs/myenv/lib/python3.9/runpy.py", line 97, in _run_module_code
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/Users/gkirabali/opt/miniconda3/envs/myenv/lib/python3.9/multiprocessing/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "/Users/gkirabali/opt/miniconda3/envs/myenv/lib/python3.9/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
    _run_code(code, mod_globals, init_globals,
  File "/Users/gkirabali/opt/miniconda3/envs/myenv/lib/python3.9/runpy.py", line 87, in _run_code
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
    exec(code, run_globals)
  File "/Users/gkirabali/examples/backprop_from_fdtd_3d.py", line 37, in <module>
    f = odt.backpropagate_3d(uSin=sinoRytov,
  File "/Users/gkirabali/opt/miniconda3/envs/myenv/lib/python3.9/site-packages/odtbrain/_alg3d_bpp.py", line 486, in backpropagate_3d
    pool4loop = mp.Pool(processes=num_cores,
  File "/Users/gkirabali/opt/miniconda3/envs/myenv/lib/python3.9/multiprocessing/context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
  File "/Users/gkirabali/opt/miniconda3/envs/myenv/lib/python3.9/multiprocessing/pool.py", line 212, in __init__
    self._repopulate_pool()
  File "/Users/gkirabali/opt/miniconda3/envs/myenv/lib/python3.9/multiprocessing/pool.py", line 303, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,
  File "/Users/gkirabali/opt/miniconda3/envs/myenv/lib/python3.9/multiprocessing/pool.py", line 326, in _repopulate_pool_static
    w.start()
  File "/Users/gkirabali/opt/miniconda3/envs/myenv/lib/python3.9/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/gkirabali/opt/miniconda3/envs/myenv/lib/python3.9/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/Users/gkirabali/opt/miniconda3/envs/myenv/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/gkirabali/opt/miniconda3/envs/myenv/lib/python3.9/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/gkirabali/opt/miniconda3/envs/myenv/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/Users/gkirabali/opt/miniconda3/envs/myenv/lib/python3.9/multiprocessing/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "/Users/gkirabali/opt/miniconda3/envs/myenv/lib/python3.9/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

**Comment by paulmueller** [comment]
Hello,

could you please check the "Note" that I made for Windows users at the top this page in the docs: https://odtbrain.readthedocs.io/en/stable/ex3d.html

If you inssert `if __name__ == '__main__':` at the beginning of the script and indent the remainder of the script, does it work for you?

**Comment by galaturka** [comment]
It works!! Your attention message is valid not only for Windows, but also for MacOS(not sure about versions). 

Thanks a lot for everything. I wish you the best.
